### ISSUE TITLE
关于RecycleViewAdapter 为啥不使用ObservableList 

### ISSUE THREAD

**Issue by open9527** [KunMinX/Strict-DataBinding#3]
ObservableList  可以直接 使用addOnListChangedCallback  监听方法去操作列表得:增,删,改,查

**Comment by KunMinX** [comment]
你想这么做的话，也可以的。

我们是考虑通过 ListAdapter 自动在内部完成 diff 操作，减少不可预期的错误。

**Comment by open9527** [comment]
我测试ListAdapter 的submitList 刷新没什么问题,但是 在加载更多的时候 加载出来的item显示得位置直接就出来了,(例如:我十条数据一页,加载第二页数据,预期显示看到第十条在最底下,实际却是直接显示到 第二页中间部分了 基本是滑动了一屏得数据 )
只能自己手动去操作scrollToPosition 方法滑动 去显示位置么?

**Comment by KunMinX** [comment]
是的，目前这种场景下我们是通过代码设置自动滑动到预期位置
