### ISSUE TITLE
设置网格布局无效

### ISSUE THREAD

**Issue by yuan1970** [KunMinX/Strict-DataBinding#7]
<androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        >

        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv"
            adapter="@{adapter}"
            submitList="@{vm.list}"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:clipToPadding="false"
            app:layoutManager="com.kunminx.binding_recyclerview.layout_manager.WrapContentGridLayoutManager"
            app:itemCount="4"
            />

    </androidx.constraintlayout.widget.ConstraintLayout>

另外没有app下的itemCount命名空间：AAPT: error: attribute itemCount (aka aks.android.rvcs:itemCount) not found.

**Comment by KunMinX** [comment]
你所提两个问题皆为 android 开发常识，与 dataBinding 及本库无关，建议自行搜索补足常识，不然很难让人帮到你。
