### ISSUE TITLE
借鉴

### ISSUE THREAD

**Issue by SunStarJ** [KunMinX/Strict-DataBinding#8]
您好，大佬，通过对于本库的学习，我这边实现了一个KT版本的，目前丢在gitee上，如果您这边允许的话想挂到jitpackio 上了https://gitee.com/Sun.start/TestBinding 这是项目地址，您看一下可以么

**Comment by KunMinX** [comment]
可以的

**Comment by SunStarJ** [comment]
好的谢谢大佬
